# -*- coding: utf-8 -*-
"""RANDOM FOREST

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DE5WiQZxMqgohAlJFIVNhqkZOz7qLX8A
"""

import pandas as pd

from sklearn.datasets import load_digits

digits=load_digits()

df = pd.DataFrame(digits.data)

df.head()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
plt.gray()#Set the color map to grayscale using plt.gray().
for i in range(4):
  plt.matshow (digits.images[i])
  #Executing the code will display the first four images of handwritten digits from the dataset in grayscale.

df["target"]=digits.target #to add the target values (labels) from the digits dataset to a DataFrame.
df

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(df.drop(["target"],axis="columns"),digits.target,test_size=0.2)

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=20)
model.fit(X_train,Y_train)

model.score(X_test,Y_test)

Y_predicted=model.predict(X_test)

Y_predicted

from sklearn.metrics import accuracy_score

accuracy_score(Y_test,Y_predicted)